const nodemailer = require('nodemailer');

const transporter = nodemailer.createTransport({
  host: process.env.EMAIL_HOST || 'smtp.gmail.com',
  port: parseInt(process.env.EMAIL_PORT) || 587,
  secure: false,
  auth: {
    user: process.env.EMAIL_USER,
    pass: process.env.EMAIL_PASS,
  },
});

/**
 * Send dashboard PDF report to the logged-in official's email.
 * @param {string} toEmail  - recipient email
 * @param {string} toName   - recipient name
 * @param {string} pdfBase64 - base64-encoded PDF string
 * @param {object} stats    - { totalCases, villages, district, dateRange }
 */
async function sendDashboardPDF(toEmail, toName, pdfBase64, stats) {
  const { totalCases, villages, district, dateRange } = stats;
  const dateLabel = dateRange || new Date().toLocaleDateString();

  const html = `
    <div style="font-family:Arial,sans-serif;max-width:600px;margin:auto;padding:24px;border:1px solid #e5e7eb;border-radius:12px;">
      <div style="background:linear-gradient(135deg,#4f46e5,#7c3aed);padding:20px 24px;border-radius:8px;margin-bottom:24px;">
        <h1 style="color:#fff;margin:0;font-size:22px;">JeevanDhara — Dashboard Report</h1>
        <p style="color:#c7d2fe;margin:4px 0 0;">Health Surveillance &amp; Outbreak Early Warning</p>
      </div>

      <p style="color:#374151;">Hi <strong>${toName}</strong>,</p>
      <p style="color:#374151;">Your dashboard report has been generated and is attached to this email.</p>

      <table style="width:100%;border-collapse:collapse;margin:16px 0;">
        <tr style="background:#f3f4f6;">
          <td style="padding:10px 14px;font-weight:600;color:#6b7280;font-size:13px;">District</td>
          <td style="padding:10px 14px;color:#111827;">${district || 'All Districts'}</td>
        </tr>
        <tr>
          <td style="padding:10px 14px;font-weight:600;color:#6b7280;font-size:13px;">Period</td>
          <td style="padding:10px 14px;color:#111827;">${dateLabel}</td>
        </tr>
        <tr style="background:#f3f4f6;">
          <td style="padding:10px 14px;font-weight:600;color:#6b7280;font-size:13px;">Total Cases</td>
          <td style="padding:10px 14px;color:#111827;">${totalCases}</td>
        </tr>
        <tr>
          <td style="padding:10px 14px;font-weight:600;color:#6b7280;font-size:13px;">Affected Villages</td>
          <td style="padding:10px 14px;color:#111827;">${villages}</td>
        </tr>
      </table>

      <p style="color:#6b7280;font-size:13px;margin-top:24px;">
        This report was automatically generated by JeevanDhara on ${new Date().toLocaleString()}.
      </p>
    </div>
  `;

  await transporter.sendMail({
    from: process.env.EMAIL_FROM || 'JeevanDhara <noreply@jeevandhara.in>',
    to: `${toName} <${toEmail}>`,
    subject: `Dashboard Report — ${district || 'All Districts'} | ${dateLabel}`,
    html,
    attachments: [
      {
        filename: `dashboard-report-${new Date().toISOString().split('T')[0]}.pdf`,
        content: pdfBase64,
        encoding: 'base64',
        contentType: 'application/pdf',
      },
    ],
  });
}

module.exports = { sendDashboardPDF };
